sawyer:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - right_j01
      - head_pan1
      - right_j11
      - right_j21
      - right_j31
      - right_j41
      - right_j51
      - right_j61
      - right_j0
      - head_pan
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: captain_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_j01
        - head_pan1
        - right_j11
        - right_j21
        - right_j31
        - right_j41
        - right_j51
        - right_j61
    - name: poirot_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_j0
        - head_pan
        - right_j1
        - right_j2
        - right_j3
        - right_j4
        - right_j5
        - right_j6
  captain_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - right_j01
      - head_pan1
      - right_j11
      - right_j21
      - right_j31
      - right_j41
      - right_j51
      - right_j61
    gains:
      right_j01:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      head_pan1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j11:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j21:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j31:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j41:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j51:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j61:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  dual_controller:
    type: velocity_controllers/JointvelocityController
    joints:
      - right_j01
      - head_pan1
      - right_j11
      - right_j21
      - right_j31
      - right_j41
      - right_j51
      - right_j61
      - right_j0
      - head_pan
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
    gains:
      right_j01:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      head_pan1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j11:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j21:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j31:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j41:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j51:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j61:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j0:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      head_pan:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  double_test_velocity:
    type: velocity_controllers/JointvelocityController
    joints:
      - right_j01
      - head_pan1
      - right_j11
      - right_j21
      - right_j31
      - right_j41
      - right_j51
      - right_j61
      - right_j0
      - head_pan
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
    gains:
      right_j01:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      head_pan1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j11:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j21:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j31:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j41:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j51:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j61:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j0:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      head_pan:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_j6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1